[project]
name = "german-labor-market-analysis-2005-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yuting Zehn", email = "yt10zehn@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "requests>=2.34.2",
    "seaborn>=0.13.2",
]

[project.scripts]
german-labor-market-analysis-2005-2025 = "german_labor_market_analysis_2005_2025:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
